spring.application.name=Crud

usernames=global
password=global

logging.level.root=INFO

logging.level.com.crudoperation.Crud=TRACE
#logging.pattern.console=%d{HH:mm:ss} [%thread] %-5level %logger - %msg%n

logging.file.name=logdata.log


management.endpoints.web.exposure.include=*
#spring.profiles.active=dev,prod


